### ISSUE TITLE
Medium Icon PNG make logo transparent

### ISSUE THREAD

**Issue by ayushere** [eminemoholic/eminemoholic.github.io#1]
medium icon makes logo transparent in light theme. due to transparency.

**Comment by adityadroid** [comment]
> medium icon makes logo transparent in light theme. due to transparency.

Thanks for pointing it out. I'll fix it.

**Comment by ayushere** [comment]
![medium](https://user-images.githubusercontent.com/44045943/69453412-dac14000-0d89-11ea-8ab3-12f553e526a0.png)
I find this cool :)

**Comment by adityadroid** [comment]
> ![medium](https://user-images.githubusercontent.com/44045943/69453412-dac14000-0d89-11ea-8ab3-12f553e526a0.png)
> I find this cool :)

Liked this one. Thanks for the suggestion. I'll update the icon :)

**Comment by adityadroid** [comment]
Updated the icon.
