### ISSUE TITLE
Blog page cannot load

### ISSUE THREAD

**Issue by cnzf1** [eminemoholic/eminemoholic.github.io#3]
Now , I'm writing a demo for web using flutter sdk 1.13+, but my http request get nothing. so I pull the adityadroid repo , And I execute command flutter run -d chrome, then I get a same problem on blog page. Would you help me ?

**Comment by adityadroid** [comment]
@cnjeffliu  Are you running it from the FlutterWeb branch? master branch contains the generated build and not the flutter code.

**Comment by adityadroid** [comment]
@cnjeffliu With recent iterations of Flutter Web opening html files directly no longer seems to work. You can use [http-server](https://www.npmjs.com/package/http-server) to serve the files and access them.

**Comment by cnzf1** [comment]
Now ,which branch should I use for running web application?

**Comment by cnzf1** [comment]
I had resolve the issue, and I just change the pubspec.yaml, but I don't understand the reason. Now I post the patch below, hope someone can specify the reason.

 environment:
-  sdk: ">=2.7.0 <3.0.0"
+  sdk: ">=2.2.0 <3.0.0"

 dependencies:
   flutter:
     sdk: flutter
-  built_collection: ^4.3.0
-  built_value: ^7.0.0
+
   # The following adds the Cupertino Icons font to your application.
   # Use with the CupertinoIcons class for iOS style icons.
   cupertino_icons: ^0.1.2
-  event_bus: ^1.0.1
-  sqflite: ^1.1.5
-  dio: ^3.0.7
-  path: ^1.5.1
-  fluttertoast: ^3.1.0
-  flutter_spinkit: "^3.1.0" #加载指示器
-  fluro: ^1.3.4
-  shared_preferences: ^0.4.3
-  protobuf: ^1.0.1
-  protoc_plugin: any
-  http: ^0.12.0+3
+  markdown: 2.1.1
+ # flutter_html: ^0.11.0
+  dio: 3.0.3
+  hive: 1.0.0
+  url_launcher: 5.2.5
+  universal_html: ^1.1.4
+#  path_provider: 1.3.1

 dev_dependencies:
   flutter_test:
     sdk: flutter
-  build_runner: ^1.7.2
-  build_web_compilers: ^2.7.1
-  built_value_generator: ^7.0.0
+
+  hive_generator: 0.5.2
+  build_runner: 1.7.1
+
