### ISSUE TITLE
Multiple Issues in Flutter 2.5

### ISSUE THREAD

**Issue by drcajunkenny** [eminemoholic/eminemoholic.github.io#9]
I have been able to remove most errors in 2.5 and commented out the blog, but the project and dark/light theme throws an error when run to Chrome to test. I have used this code before and it was very helpful to making my portfolio, but jump ahead two years to try it again and no dice.  Thanks for any updated versions.

**Comment by adityadroid** [comment]
@drcajunkenny Thank you for bringing this to my notice. I'll try updating the website over the weekend. Can you create a PR with the fixes you have done on your end?

**Comment by adityadroid** [comment]
Fixed these @drcajunkenny
